name: Kubescape
description: Run Kubescape scan
inputs:
  failedThreshold:
    description: |
      Failure threshold is the percent above which the command fails and 
      returns exit code 1 (default 0 i.e, action fails if any control fails)
    required: false
  files:
    description: |
      Path to the configuration yaml to scan
    required: false
  frameworks:
    description: |
      List of all frameworks to scan. Run kubescape list frameworks with 
      the Kubescape CLI to get a list of all frameworks. Either frameworks 
      have to be specified or controls.
    required: false
  controls:
    description: |
      List of all controls to scan. Run kubescape list controls with the 
      Kubescape CLI to get a list of all controls. Either frameworks 
      have to be specified or controls.
    required: false
  account:
    description: |
      Account-id for the SAS.
      Used for custom configuration, such as frameworks, control configuration, etc.
    required: false
  thresholdCritical:
    description: |
      Threshold Critical is the number or more of critical controls that failed 
      and returns exit code 1
    required: false
  thresholdHigh:
    description: |
      Threshold High is the number or more of high controls that failed 
      and returns exit code 1
    required: false
  thresholdMedium:
    description: |
      Threshold Medium is the number or more of medium controls that failed 
      and returns exit code 1
    required: false
  thresholdLow:
    description: |
      Threshold Low is the number or more of low controls that failed 
      and returns exit code 1
    required: false
  format:
    description: |
      Output format
      Run `kubescape scan -h` for listing supported formats
    required: false
    default: junit
runs:
  using: docker
  image: quay.io/kubescape/github-actions

