name: Kubescape scanning for misconfigurations
on:
  release:
    types: [released]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      # with:
      #   failedThreshold: 100
      #   # Optional - Add Kubescape cloud account ID.
      #   account: ${{secrets.KUBESCAPE_ACCOUNT}}
      #   # Optional - Scan a specific path. Default will scan all
      #   files: "examples/*.yaml"
    - name: Archive kubescape scan results
      uses: actions/upload-artifact@v2
      with:
        name: kubescape
        path: results.xml
    - name: Publish Unit Test Results
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: "*.xml" 