name: Example
on: [push, pull_request]
jobs:
  kubescape-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dwertent/github-action@main
        with:
          threshold: "0"
          # account: ${{ github.KUBESCAPE_ACCOUNT }}
      - name: Archive kubescape scan results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: kubescape-scan-report
          path: results.xml

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**.xml" 
          require_tests: false
          fail_on_failure: false
          detailed_summary: true